version: "3"
services:

  web:
    build: .
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 100m
    ports:
      - "80:8080"
    links:
      - mongo
    env_file:
        DO-production.env

  mongo:
    volumes:
        - db:/data/db
    env_file:
        DO-production.env
    image: mongo:latest
    command: mongod --port 27017
    expose:
        - "27017"

volumes:
    db:
