version: "2"

services:
  web:
    container_name: web
    build: .
    restart: always
    ports:
        - "3000:3000"
    env_file:
        - DO-production.env
    environment:
        - MONGODB_URI=mongodb://mongo/db
    depends_on:
        - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
        - MONGO_INITDB_DATABASE=db
    ports:
        - "27018:27017"
    volumes:
        - db:/data/db

  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data:/usr/src/app/data
      
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

volumes:
    db:
