version: 2
jobs:
  build:
    working_directory: ~/codesnatch
    docker:
      - image: circleci/node:8-alpine
      - image: circleci/mongo:latest
      - image: circleci/nginx:mainline-alpine
    steps:
      - checkout
      - run: 
        - name: update-npm
        - command: 'npm update'

      - run:
        - name: test-npm
        - command: 'npm test'
        